// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyBaseInclude.h"
#include "ManiacManfredInterfaces.h"
#include "ManiacManfredArticyTypes.generated.h"


/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef MouseCursor */
class EManiacManfredMouseCursor : uint8
{
	Point = 0,
	Take = 1,
	Speak = 2,
	Walk = 3,
	Inspect = 4,
	Use = 5,
	Auto = 255,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef ShapeType */
class EManiacManfredShapeType : uint8
{
	Invalid = 0,
	Spot = 1,
	Circle = 2,
	Rectangle = 3,
	Path = 4,
	Polygon = 5,
	Link = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef SelectabilityModes */
class EManiacManfredSelectabilityModes : uint8
{
	Unselectable = 0,
	Selectable = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef OutlineStyle */
class EManiacManfredOutlineStyle : uint8
{
	Solid = 0,
	Dot = 1,
	Dash = 2,
	DashDot = 3,
	DashDotDot = 4,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef VisibilityModes */
class EManiacManfredVisibilityModes : uint8
{
	Invisible = 0,
	Visible = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PathCaps */
class EManiacManfredPathCaps : uint8
{
	ColoredDot = 0,
	None = 1,
	LineArrowHead = 2,
	FilledArrowHead = 3,
	Diamond = 4,
	Square = 5,
	Disc = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef LocationAnchorSize */
class EManiacManfredLocationAnchorSize : uint8
{
	Small = 0,
	Medium = 1,
	Large = 2,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PreviewImageViewBoxModes */
class EManiacManfredPreviewImageViewBoxModes : uint8
{
	FromAsset = 0,
	Custom = 1,
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef FlowFragment */
UCLASS(BlueprintType)
class UManiacManfredFlowFragment : public UArticyFlowFragment,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Dialogue */
UCLASS(BlueprintType)
class UManiacManfredDialogue : public UArticyDialogue,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef DialogueFragment */
UCLASS(BlueprintType)
class UManiacManfredDialogueFragment : public UArticyDialogueFragment,
 public IArticyObjectWithMenuText,
 public IArticyObjectWithStageDirections,
 public IArticyObjectWithSpeaker,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="MenuText"))
	FText MenuText = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StageDirections"))
	FText StageDirections = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Speaker"))
	FArticyId Speaker;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Soundfile Feature */
UCLASS(BlueprintType)
class UManiacManfredSoundfileFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Sound"))
	FArticyId Sound;
};
/** UCLASS generated from Articy DialogChoice Feature */
UCLASS(BlueprintType)
class UManiacManfredDialogChoiceFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Required item"))
	FArticyId RequiredItem;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Location change"))
	FArticyId LocationChange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Morale Change"))
	UArticyScriptInstruction* MoraleChange = nullptr;
};
/** UCLASS generated from ArticyObjectDef DialogChoice */
UCLASS(BlueprintType)
class UManiacManfredDialogChoice : public UManiacManfredDialogueFragment,
 public IManiacManfredObjectWithSoundfileFeature,
 public IManiacManfredObjectWithDialogChoiceFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithSoundfileFeature implementation */
	UManiacManfredSoundfileFeature* GetFeatureSoundfile() const override
	{
		return Soundfile;
	}
	/** IManiacManfredObjectWithDialogChoiceFeature implementation */
	UManiacManfredDialogChoiceFeature* GetFeatureDialogChoice() const override
	{
		return DialogChoice;
	}
	/** Soundfile */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredSoundfileFeature* Soundfile;
	/** DialogChoice */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredDialogChoiceFeature* DialogChoice;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Hub */
UCLASS(BlueprintType)
class UManiacManfredHub : public UArticyHub,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Comment */
UCLASS(BlueprintType)
class UManiacManfredComment : public UArticyComment,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedBy"))
	FString CreatedBy = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedOn"))
	FDateTime CreatedOn;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Jump */
UCLASS(BlueprintType)
class UManiacManfredJump : public UArticyJump,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Entity */
UCLASS(BlueprintType)
class UManiacManfredEntity : public UArticyEntity,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy ItemCombination Feature */
UCLASS(BlueprintType)
class UManiacManfredItemCombinationFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Valid combination"))
	FArticyId ValidCombination;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Combination result"))
	FArticyId CombinationResult;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Link if success"))
	FArticyId LinkIfSuccess;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Link if failure"))
	FArticyId LinkIfFailure;
};
/** UCLASS generated from Articy VariableBinding Feature */
UCLASS(BlueprintType)
class UManiacManfredVariableBindingFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Variable"))
	UArticyScriptCondition* VariableName = nullptr;
};
/** UCLASS generated from ArticyObjectDef Item */
UCLASS(BlueprintType)
class UManiacManfredItem : public UManiacManfredEntity,
 public IManiacManfredObjectWithItemCombinationFeature,
 public IManiacManfredObjectWithVariableBindingFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithItemCombinationFeature implementation */
	UManiacManfredItemCombinationFeature* GetFeatureItemCombination() const override
	{
		return ItemCombination;
	}
	/** IManiacManfredObjectWithVariableBindingFeature implementation */
	UManiacManfredVariableBindingFeature* GetFeatureVariableBinding() const override
	{
		return VariableBinding;
	}
	/** ItemCombination */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredItemCombinationFeature* ItemCombination;
	/** VariableBinding */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredVariableBindingFeature* VariableBinding;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Character Feature */
UCLASS(BlueprintType)
class UManiacManfredCharacterFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Age"))
	float Age = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Voice Actor"))
	FString VoiceActor = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Background Story"))
	FString BackgroundStory = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Motivation"))
	FString Motivation = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Likes"))
	TArray<FArticyId> Likes;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Dislikes"))
	TArray<FArticyId> Dislikes;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Liked by"))
	TArray<FArticyId> LikedBy;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Disliked by"))
	TArray<FArticyId> DislikedBy;
};
/** UCLASS generated from ArticyObjectDef Character */
UCLASS(BlueprintType)
class UManiacManfredCharacter : public UManiacManfredEntity,
 public IManiacManfredObjectWithCharacterFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithCharacterFeature implementation */
	UManiacManfredCharacterFeature* GetFeatureCharacter() const override
	{
		return Character;
	}
	/** Character */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredCharacterFeature* Character;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Morale Feature */
UCLASS(BlueprintType)
class UManiacManfredMoraleFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Morale Value"))
	int32 MoraleValue = 0;
};
/** UCLASS generated from ArticyObjectDef Player_Character */
UCLASS(BlueprintType)
class UManiacManfredPlayer_Character : public UManiacManfredEntity,
 public IManiacManfredObjectWithMoraleFeature,
 public IManiacManfredObjectWithCharacterFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithMoraleFeature implementation */
	UManiacManfredMoraleFeature* GetFeatureMorale() const override
	{
		return Morale;
	}
	/** IManiacManfredObjectWithCharacterFeature implementation */
	UManiacManfredCharacterFeature* GetFeatureCharacter() const override
	{
		return Character;
	}
	/** Morale */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredMoraleFeature* Morale;
	/** Character */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredCharacterFeature* Character;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Location */
UCLASS(BlueprintType)
class UManiacManfredLocation : public UArticyLocation,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy LocationSettings Feature */
UCLASS(BlueprintType)
class UManiacManfredLocationSettingsFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Initial dialog"))
	FArticyId InitialDialog;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Is start location"))
	bool IsStartLocation = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Backgrounds"))
	TArray<FArticyId> Backgrounds;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Initial dialog condition"))
	UArticyScriptCondition* InitialDialogCondition = nullptr;
};
/** UCLASS generated from ArticyObjectDef LocationSettings */
UCLASS(BlueprintType)
class UManiacManfredLocationSettings : public UManiacManfredLocation,
 public IManiacManfredObjectWithSoundfileFeature,
 public IManiacManfredObjectWithLocationSettingsFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithSoundfileFeature implementation */
	UManiacManfredSoundfileFeature* GetFeatureSoundfile() const override
	{
		return Soundfile;
	}
	/** IManiacManfredObjectWithLocationSettingsFeature implementation */
	UManiacManfredLocationSettingsFeature* GetFeatureLocationSettings() const override
	{
		return LocationSettings;
	}
	/** Soundfile */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredSoundfileFeature* Soundfile;
	/** LocationSettings */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredLocationSettingsFeature* LocationSettings;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Spot */
UCLASS(BlueprintType)
class UManiacManfredSpot : public UArticySpot,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EManiacManfredVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EManiacManfredOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EManiacManfredSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Zone */
UCLASS(BlueprintType)
class UManiacManfredZone : public UArticyZone,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EManiacManfredShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EManiacManfredVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EManiacManfredOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EManiacManfredSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy ZoneCondition Feature */
UCLASS(BlueprintType)
class UManiacManfredZoneConditionFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="If condition is true"))
	FArticyId IfConditionTrue;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="If condition is false"))
	FArticyId IfConditionFalse;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Cursor if condition is true"))
	EManiacManfredMouseCursor CursorIfConditionTrue;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Cursor if condition is false"))
	EManiacManfredMouseCursor CursorIfConditionFalse;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Item to interact with"))
	FArticyId ItemToInteractWith;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Link if item is valid"))
	FArticyId LinkIfItemValid;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Link if item is invalid"))
	FArticyId LinkIfItemInvalid;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Click condition"))
	UArticyScriptCondition* ClickCondition = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="On click instruction"))
	UArticyScriptInstruction* OnClickInstruction = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Interaction condition"))
	UArticyScriptCondition* InteractionCondition = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Instruction if item is valid"))
	UArticyScriptInstruction* InstructionIfItemValid = nullptr;
};
/** UCLASS generated from ArticyObjectDef Conditional_Zone */
UCLASS(BlueprintType)
class UManiacManfredConditional_Zone : public UManiacManfredZone,
 public IManiacManfredObjectWithZoneConditionFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithZoneConditionFeature implementation */
	UManiacManfredZoneConditionFeature* GetFeatureZoneCondition() const override
	{
		return ZoneCondition;
	}
	/** ZoneCondition */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredZoneConditionFeature* ZoneCondition;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Path */
UCLASS(BlueprintType)
class UManiacManfredPath : public UArticyPath,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EManiacManfredVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EManiacManfredSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EManiacManfredOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StartCap"))
	EManiacManfredPathCaps StartCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="EndCap"))
	EManiacManfredPathCaps EndCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="LineWidth"))
	float LineWidth = 0.f;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Link */
UCLASS(BlueprintType)
class UManiacManfredLink : public UArticyLink,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithTarget,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Target"))
	FArticyId Target;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EManiacManfredVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EManiacManfredSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Asset */
UCLASS(BlueprintType)
class UManiacManfredAsset : public UArticyAsset,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Filename"))
	FString Filename = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OriginalSource"))
	FString OriginalSource = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef BackgroundImage */
UCLASS(BlueprintType)
class UManiacManfredBackgroundImage : public UManiacManfredAsset,
 public IManiacManfredObjectWithVariableBindingFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithVariableBindingFeature implementation */
	UManiacManfredVariableBindingFeature* GetFeatureVariableBinding() const override
	{
		return VariableBinding;
	}
	/** VariableBinding */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredVariableBindingFeature* VariableBinding;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Condition */
UCLASS(BlueprintType)
class UManiacManfredCondition : public UArticyCondition,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptCondition* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Instruction */
UCLASS(BlueprintType)
class UManiacManfredInstruction : public UArticyInstruction,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptInstruction* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationText */
UCLASS(BlueprintType)
class UManiacManfredLocationText : public UArticyLocationText,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EManiacManfredShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EManiacManfredVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EManiacManfredOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EManiacManfredSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedWidth"))
	float ForcedWidth = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedHeight"))
	float ForcedHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationImage */
UCLASS(BlueprintType)
class UManiacManfredLocationImage : public UArticyLocationImage,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EManiacManfredShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EManiacManfredVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EManiacManfredOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EManiacManfredSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ClipRect"))
	FArticyRect ClipRect;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageOpacity"))
	float ImageOpacity = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageAsset"))
	FArticyId ImageAsset;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageWidth"))
	int32 CachedImageWidth = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageHeight"))
	int32 CachedImageHeight = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy DisplayCondition Feature */
UCLASS(BlueprintType)
class UManiacManfredDisplayConditionFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Show me if"))
	UArticyScriptCondition* ShowMeIf = nullptr;
};
/** UCLASS generated from ArticyObjectDef DisplayCondition */
UCLASS(BlueprintType)
class UManiacManfredDisplayCondition : public UManiacManfredLocationImage,
 public IManiacManfredObjectWithDisplayConditionFeature
{
	GENERATED_BODY()
	
public:
	
	/** IManiacManfredObjectWithDisplayConditionFeature implementation */
	UManiacManfredDisplayConditionFeature* GetFeatureDisplayCondition() const override
	{
		return DisplayCondition;
	}
	/** DisplayCondition */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UManiacManfredDisplayConditionFeature* DisplayCondition;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Document */
UCLASS(BlueprintType)
class UManiacManfredDocument : public UArticyDocument,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef TextObject */
UCLASS(BlueprintType)
class UManiacManfredTextObject : public UArticyTextObject,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef UserFolder */
UCLASS(BlueprintType)
class UManiacManfredUserFolder : public UArticyUserFolder,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithShortId,
 public IArticyObjectWithZIndex
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
};
