// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ManiacManfredInterfaces.generated.h"


/** UNINTERFACE generated from Articy Soundfile Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithSoundfileFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithSoundfileFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredSoundfileFeature* GetFeatureSoundfile() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy DialogChoice Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithDialogChoiceFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithDialogChoiceFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredDialogChoiceFeature* GetFeatureDialogChoice() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy ItemCombination Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithItemCombinationFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithItemCombinationFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredItemCombinationFeature* GetFeatureItemCombination() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy VariableBinding Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithVariableBindingFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithVariableBindingFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredVariableBindingFeature* GetFeatureVariableBinding() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Character Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithCharacterFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithCharacterFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredCharacterFeature* GetFeatureCharacter() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Morale Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithMoraleFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithMoraleFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredMoraleFeature* GetFeatureMorale() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy LocationSettings Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithLocationSettingsFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithLocationSettingsFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredLocationSettingsFeature* GetFeatureLocationSettings() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy ZoneCondition Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithZoneConditionFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithZoneConditionFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredZoneConditionFeature* GetFeatureZoneCondition() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy DisplayCondition Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="ManiacManfred Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UManiacManfredObjectWithDisplayConditionFeature : public UInterface { GENERATED_BODY() };
class IManiacManfredObjectWithDisplayConditionFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UManiacManfredDisplayConditionFeature* GetFeatureDisplayCondition() const
	{
		return nullptr;
	}
};
